### ISSUE TITLE
Unable to build in an ionic - cordova app

### ISSUE THREAD

**Issue by Arj-Shankar** [karandpr/cordova-plugin-android-rootbeer#10]
Getting the following exception when trying to create the android build 

 `Could not find method compile() for arguments [com.github.scottyab:rootbeer:0.0.8] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
`

Using the following - 

cordova-android 11
Java 11
Gradle 6.8.3
Intel Mac (v12.0.1)

-----
Tried removing and re-adding the platform and the plugin multiple times.

Installed the plugin by running the command
`ionic cordova plugin add cordova-plugin-android-rootbeer@0.0.8`

**Comment by karandpr** [comment]
Okay. This is strange but let me check over the weekend.

**Comment by CaioMelo8** [comment]
@Arj-Shankar, `cordova-android@11` uses Gradle `7.4.2` by default, which has already removed the `compile()` configuration that's deprecated for a good while. Now `implementation()` must be used instead.

The simple fix is to update the plugin `build-extras.gradle` to something like this:

```groovy
repositories{
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'com.github.scottyab:rootbeer:0.0.8'
}
```
